## Deliverable 2. Create a Customer Travel Destinations Map.

In [37]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
import sys
sys.path.append("..")
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [39]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head(20)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Severo-Kurilsk,RU,50.6789,156.1250,53.35,69,100,6.11,overcast clouds
1,1,Port Hedland,AU,-20.3167,118.5667,80.65,65,90,8.05,overcast clouds
2,2,Punta Arenas,CL,-53.1500,-70.9167,35.71,93,0,5.75,clear sky
3,3,Alice Springs,AU,-23.7000,133.8833,74.21,21,9,11.99,clear sky
4,4,Lenger,KZ,42.1830,69.8839,76.44,22,14,2.53,few clouds
5,5,Mataura,NZ,-46.1927,168.8643,52.30,72,23,2.68,few clouds
6,6,Barrow,US,71.2906,-156.7887,33.82,80,90,12.66,overcast clouds
7,7,Cabo San Lucas,MX,22.8909,-109.9124,86.81,66,0,6.62,clear sky
8,8,Port Hardy,CA,50.6996,-127.4199,55.58,76,75,16.11,light rain
9,9,Kindu,CD,-2.9500,25.9500,67.87,72,60,1.83,broken clouds
10,10,Krasnoarmeysk,RU,51.0239,45.6969,65.16,83,21,1.34,few clouds
11,11,Mitsamiouli,KM,-11.3847,43.2844,76.19,67,0,8.68,clear sky
12,12,Saint-Dizier,FR,48.4167,5.0833,59.05,97,96,4.00,overcast clouds
13,13,Namibe,AO,-15.1961,12.1522,70.14,65,1,7.92,clear sky
14,14,Lorengau,PG,-2.0226,147.2712,83.61,74,15,10.98,light rain
15,15,Sao Filipe,CV,14.8961,-24.4956,73.53,83,47,4.12,scattered clouds
16,16,Saint-Philippe,RE,-21.3585,55.7679,71.47,79,96,14.79,overcast clouds
17,17,San Jose,US,37.3394,-121.8950,71.46,54,20,5.99,few clouds
18,18,Lavrentiya,RU,65.5833,-171.0000,36.99,96,100,6.22,overcast clouds
19,19,Luderitz,NaN,-26.6481,15.1594,66.09,45,59,4.25,broken clouds

In [43]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the min temp you would like for your trip?"))
max_temp = float(input("What is the max temp you would like for your trip?"))

What is the min temp you would like for your trip?70
What is the max temp you would like for your trip?85

In [46]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) & (city_data_df["Max Temp"] <= max_temp)]
preferred_cities_df

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Port Hedland,AU,-20.3167,118.5667,80.65,65,90,8.05,overcast clouds
3,3,Alice Springs,AU,-23.7000,133.8833,74.21,21,9,11.99,clear sky
4,4,Lenger,KZ,42.1830,69.8839,76.44,22,14,2.53,few clouds
11,11,Mitsamiouli,KM,-11.3847,43.2844,76.19,67,0,8.68,clear sky
13,13,Namibe,AO,-15.1961,12.1522,70.14,65,1,7.92,clear sky
...,...,...,...,...,...,...,...,...,...,...
659,659,Laurinburg,US,34.7741,-79.4628,79.02,92,1,5.75,clear sky
663,663,Wewak,PG,-3.5534,143.6268,84.99,68,4,8.63,clear sky
664,664,Rock Sound,BS,24.9000,-76.2000,79.68,76,40,9.84,scattered clouds
666,666,Lander,US,42.8330,-108.7307,70.20,30,1,11.50,clear sky
667,667,Virginia Beach,US,36.8529,-75.9780,76.01,91,90,3.44,moderate rain

In [48]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

Unnamed: 0             0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [24]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [49]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Port Hedland,AU,80.65,overcast clouds,-20.3167,118.5667,
3,Alice Springs,AU,74.21,clear sky,-23.7000,133.8833,
4,Lenger,KZ,76.44,few clouds,42.1830,69.8839,
11,Mitsamiouli,KM,76.19,clear sky,-11.3847,43.2844,
13,Namibe,AO,70.14,clear sky,-15.1961,12.1522,
14,Lorengau,PG,83.61,light rain,-2.0226,147.2712,
15,Sao Filipe,CV,73.53,scattered clouds,14.8961,-24.4956,
16,Saint-Philippe,RE,71.47,overcast clouds,-21.3585,55.7679,
17,San Jose,US,71.46,few clouds,37.3394,-121.8950,
24,Rikitea,PF,76.15,overcast clouds,-23.1203,-134.9692,

In [50]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index,row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"] 
    lng = row["Lng"] 
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url,params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index,"Hotel Name"] = hotels["results"][0]["name"]
        
    except Exception as e:
        print(e)
        print("Hotel not found... skipping.")

list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.
list index out of range
Hotel not found... skipping.

In [79]:
# 7. Drop the rows where there is no Hotel Name.

import numpy as np

hotel_df["Hotel Name"].replace('', np.nan, inplace=True)
hotel_df.dropna(subset=['Hotel Name'], inplace=True)
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Port Hedland,AU,80.65,overcast clouds,-20.3167,118.5667,The Esplanade Hotel
3,Alice Springs,AU,74.21,clear sky,-23.7000,133.8833,Desert Palms Alice Springs
4,Lenger,KZ,76.44,few clouds,42.1830,69.8839,Gostevoy Dom 1
11,Mitsamiouli,KM,76.19,clear sky,-11.3847,43.2844,Foyer ADM
13,Namibe,AO,70.14,clear sky,-15.1961,12.1522,Hotel Chik Chik Namibe
...,...,...,...,...,...,...,...
659,Laurinburg,US,79.02,clear sky,34.7741,-79.4628,"Holiday Inn Express & Suites Laurinburg, an IH..."
663,Wewak,PG,84.99,clear sky,-3.5534,143.6268,In Wewak Boutique Hotel
664,Rock Sound,BS,79.68,scattered clouds,24.9000,-76.2000,Rock Sound Club
666,Lander,US,70.20,clear sky,42.8330,-108.7307,"Holiday Inn Express & Suites Lander, an IHG Hotel"
667,Virginia Beach,US,76.01,moderate rain,36.8529,-75.9780,Hilton Virginia Beach Oceanfront

In [80]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [86]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [87]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))